apiVersion: v1

kind: Pod

metadata:

  name: nginx

  labels:
    app: nginx-server
    type: server

spec:
  containers:
  - name: nginxs
    image: nginx
    ports:
    - containerPort: 80
    imagePullPolicy: IfNotPresent
