version: '3.8'

services:
   backend:
      build: ./
      ports:
        - "80:3000"
      container_name: backend-app
    #   depends_on:
        #    - database
   database: 
       image: mysql
       environment:
           MYSQL_ROOT_PASSWORD: my-secret-pw
           MYSQL_DATABASE: 'products'
       volumes: 
           - app-data:/var/lib/mysql 
       container_name: mysql-db 
volumes:
   app-data: