version: '3.8'


services:
   database: 
       image: mysql
       expose:
         - "3306"
       ports:
         - "3306:3306"
       environment:
           MYSQL_ROOT_PASSWORD: my-secret-pw
           MYSQL_DATABASE: 'products'
       volumes: 
           - app-data:/var/lib/mysql 
       
   backend:
      build: ./
      ports:
        - "80:3000"
      depends_on:
           - database
  
volumes:
   app-data: