apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
       app: nginx
       type: server
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      imagePullPolicy:  IfNotPresent